### ISSUE TITLE
<Item1 Update=... with %(Item2.xxx reference code example does not work

### ISSUE THREAD

**Issue by macnuts** [MicrosoftDocs/visualstudio-docs#5335]
Second code example of **Updating metadata on items in an ItemGroup outside of a Target** does not work. Items are updated as if no Item2 were found.
Price is null and material is never premium for all Item1 items in the target output.
MSBuild version 16.5.1.21502.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4c1957-1da1-073e-e5d2-b88dbb6e4f0c
* Version Independent ID: da079116-5827-d486-271b-9e2cb10bf063
* Content: [MSBuild Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-items.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@macnuts I reproduced the issue. Thanks for reporting the problem.
@rainersigwald The output doesn't match what's expected 

```xml
<Project>
    <ItemGroup>
        <Item1 Include="stapler">
            <Size>medium</Size>
            <Color>black</Color>
            <Material>plastic</Material>
        </Item1>
        <Item1 Include="pencil">
            <Size>small</Size>
            <Color>yellow</Color>
            <Material>wood</Material>
        </Item1>
        <Item1 Include="eraser">
            <Size>small</Size>
            <Color>red</Color>
            <Material>gum</Material>
        </Item1>
        <Item1 Include="notebook">
            <Size>large</Size>
            <Color>white</Color>
            <Material>paper</Material>
        </Item1>

        <Item2 Include="pencil">
            <Size>MEDIUM</Size>
            <Color>RED</Color>
            <Material>PLASTIC</Material>
            <Price>10</Price>
        </Item2>

        <Item3 Include="notebook">
            <Size>SMALL</Size>
            <Color>BLUE</Color>
            <Price>20</Price>
        </Item3>

        <!-- Metadata can be expressed either as attributes or as elements -->
        <Item1 Update="@(Item2);er*r;@(Item3)" Size="%(Size)" Color="%(Item2.Color)" Price="%(Item3.Price)" Model="2020">
            <Material Condition="'%(Item2.Material)' != ''">Premium %(Item2.Material)</Material>
        </Item1>
    </ItemGroup>

    <Target Name="MyTarget">
        <Message Text="Item1: %(Item1.Identity)
    Size: %(Item1.Size)
    Color: %(Item1.Color)
    Material: %(Item1.Material)
    Price: %(Item1.Price)
    Model: %(Item1.Model)" />
    </Target>
</Project>

<!--  
Item1: stapler
    Size: medium
    Color: black
    Material: plastic
    Price:
    Model:
Item1: pencil
    Size: small
    Color: RED
    Material: Premium PLASTIC
    Price:
    Model: 2020
Item1: eraser
    Size: small
    Color:
    Material: gum
    Price:
    Model: 2020
Item1: notebook
    Size: large
    Color:
    Material: paper
    Price: 20
    Model: 2020
-->
```

Actual output:
```
  Item1: stapler
      Size: medium
      Color: black
      Material: plastic
      Price:
      Model:
  Item1: pencil
      Size: small
      Color:
      Material: wood
      Price:
      Model: 2020
  Item1: eraser
      Size: small
      Color:
      Material: gum
      Price:
      Model: 2020
  Item1: notebook
      Size: large
      Color:
      Material: paper
      Price:
      Model: 2020
```
