### ISSUE TITLE
Debugging with isolation doesn't seem to work

### ISSUE THREAD

**Issue by LanderVe** [MicrosoftDocs/visualstudio-docs#6169]
Any REST API call to `http://landerve-5ce9.bikeapp.gateway.20.62.235.126.nip.io/api` returns a 404. Not sure if this is a product issue, or if this document doesn't contain the steps to make it work. The (cloned) ingress does have a rule for this URL.

```yaml
spec:
  rules:
  - host: landerve-5ce9.bikeapp.gateway.20.62.235.126.nip.io
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: http
        path: /
        pathType: ImplementationSpecific
```

And the Gateway application does seem to do the header forwarding.
What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Use Bridge to Kubernetes with Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019#next-steps)
* Content Source: [docs/containers/bridge-to-kubernetes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/bridge-to-kubernetes.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**
